opt_in_rules: # some rules are only opt-in
#  - explicit_self
  - explicit_init
  - empty_count
  - empty-string
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Pods
line_length:
  warning: 120
#  ignores_function_declarations: true
  ignores_comments: true
  ignores_interpolated_strings: true
  ignores_urls: true
